//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code_Lib
    {
        public string code_type { get; set; }
        public Nullable<int> get_year { get; set; }
        public Nullable<int> get_month { get; set; }
        public Nullable<int> get_day { get; set; }
        public Nullable<int> codeleng { get; set; }
        public Nullable<int> maxnum { get; set; }
        public string last_code { get; set; }
        public string memo { get; set; }
        public Nullable<int> editid { get; set; }
        public Nullable<System.DateTime> edittime { get; set; }
        public string src { get; set; }
        public string menu { get; set; }
        public byte[] RV { get; set; }
    }
}
