//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class download
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<byte> ctype { get; set; }
        public string filename { get; set; }
        public Nullable<int> filesize { get; set; }
        public string memo { get; set; }
        public Nullable<byte> lev { get; set; }
        public Nullable<int> down_qty { get; set; }
        public byte pub_status { get; set; }
        public Nullable<int> audit { get; set; }
        public Nullable<System.DateTime> audit_time { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<System.DateTime> utime { get; set; }
        public string gov_dept { get; set; }
    }
}
