//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_Bank
    {
        public int id { get; set; }
        public string zhname { get; set; }
        public string yhzh { get; set; }
        public string yhname { get; set; }
        public string remark { get; set; }
        public Nullable<decimal> dcMoney { get; set; }
    }
}
