//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_bhd_master
    {
        public short agent { get; set; }
        public System.DateTime sdate { get; set; }
        public short sh_id { get; set; }
        public short cid { get; set; }
        public System.DateTime cdate { get; set; }
        public byte u_state { get; set; }
        public Nullable<short> scode { get; set; }
        public string v_code { get; set; }
        public Nullable<byte> convey { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<short> iType { get; set; }
        public Nullable<System.DateTime> ydate { get; set; }
        public Nullable<int> del_flag { get; set; }
    }
}
