//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_bhd
    {
        public int id { get; set; }
        public short ywy { get; set; }
        public Nullable<short> sh_id { get; set; }
        public Nullable<System.DateTime> sh_time { get; set; }
        public Nullable<int> sh_flag { get; set; }
        public short zdr { get; set; }
        public System.DateTime ctime { get; set; }
        public byte status { get; set; }
        public Nullable<short> scode { get; set; }
        public string code { get; set; }
        public Nullable<short> uid { get; set; }
        public Nullable<System.DateTime> utime { get; set; }
        public Nullable<short> vtype { get; set; }
        public Nullable<System.DateTime> ydate { get; set; }
        public Nullable<int> del_flag { get; set; }
        public Nullable<int> c_status { get; set; }
    }
}
