//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_bh_info
    {
        public int id { get; set; }
        public string b_no { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<System.DateTime> bh_time { get; set; }
        public Nullable<int> b_status { get; set; }
        public Nullable<int> b_type { get; set; }
        public Nullable<System.DateTime> zd_time { get; set; }
        public Nullable<System.DateTime> bt_change_time { get; set; }
        public Nullable<int> o_id { get; set; }
        public Nullable<int> scode { get; set; }
        public Nullable<int> a_id { get; set; }
        public Nullable<System.DateTime> a_time { get; set; }
        public Nullable<byte> del_flag { get; set; }
        public Nullable<byte> sh_flag { get; set; }
        public Nullable<int> ush_id { get; set; }
    }
}
