//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_bhd_detail
    {
        public int item_id { get; set; }
        public decimal num { get; set; }
        public string remark { get; set; }
        public Nullable<short> scode { get; set; }
        public Nullable<decimal> bsl { get; set; }
        public Nullable<decimal> @out { get; set; }
        public Nullable<decimal> finish { get; set; }
        public Nullable<decimal> dsl { get; set; }
        public Nullable<int> del_flag { get; set; }
        public string v_code { get; set; }
    }
}
