//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_cxtj
    {
        public int id { get; set; }
        public string v_code { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<System.DateTime> utime { get; set; }
        public Nullable<int> sh_id { get; set; }
        public Nullable<System.DateTime> sxr { get; set; }
        public Nullable<int> sh_flag { get; set; }
        public Nullable<int> del_flag { get; set; }
    }
}
