//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_dborjb
    {
        public int id { get; set; }
        public Nullable<int> scode { get; set; }
        public string pc_name { get; set; }
        public Nullable<int> bcode { get; set; }
        public Nullable<int> usr_id { get; set; }
        public string cname { get; set; }
        public Nullable<decimal> dbje { get; set; }
        public Nullable<System.DateTime> dtime { get; set; }
        public Nullable<decimal> jbje { get; set; }
        public Nullable<int> jcount { get; set; }
        public Nullable<decimal> tkje { get; set; }
        public Nullable<decimal> qkje { get; set; }
        public Nullable<System.DateTime> jtime { get; set; }
        public string pc_code { get; set; }
        public Nullable<decimal> item_count { get; set; }
        public Nullable<decimal> all_je { get; set; }
    }
}
