//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_dept_info
    {
        public int scode { get; set; }
        public Nullable<byte> bm { get; set; }
        public Nullable<byte> bm1 { get; set; }
        public Nullable<byte> bm2 { get; set; }
        public string cname { get; set; }
        public string sLinkMan { get; set; }
        public string sTel { get; set; }
        public string sAddress { get; set; }
        public Nullable<int> iCreateItem { get; set; }
        public Nullable<int> iCreateSup { get; set; }
        public Nullable<int> iCreateCust { get; set; }
        public Nullable<int> ipPriceType { get; set; }
        public Nullable<int> iSingleVip { get; set; }
        public Nullable<int> iDistribute { get; set; }
        public string sPricetype { get; set; }
        public Nullable<byte> iJM { get; set; }
        public Nullable<short> iCreateVip { get; set; }
        public Nullable<short> iacctype { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<byte> del_flag { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<byte> ilevel { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> sort { get; set; }
    }
}
