//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_hs_jsd
    {
        public int ihs { get; set; }
        public int ijsno { get; set; }
        public string sjsno { get; set; }
        public System.DateTime djsdate { get; set; }
        public short ijsname { get; set; }
        public short iczname { get; set; }
        public short iskname { get; set; }
        public string smemo { get; set; }
        public Nullable<int> iBz { get; set; }
    }
}
