//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_istore_detail
    {
        public int scode { get; set; }
        public int item_id { get; set; }
        public string tm { get; set; }
        public string cname { get; set; }
        public string spec { get; set; }
        public Nullable<decimal> hpack_size { get; set; }
        public Nullable<int> unit { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> jj_price { get; set; }
        public Nullable<decimal> ls_price { get; set; }
        public string batch_no { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<System.DateTime> utime { get; set; }
        public string srvoucher { get; set; }
        public Nullable<byte> flag { get; set; }
        public Nullable<decimal> hy_price { get; set; }
    }
}
