//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_item_lb
    {
        public byte bm { get; set; }
        public Nullable<byte> bm1 { get; set; }
        public Nullable<byte> bm2 { get; set; }
        public Nullable<byte> bm3 { get; set; }
        public string cname { get; set; }
        public int lb_code { get; set; }
        public Nullable<byte> cid { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<byte> ilevel { get; set; }
    }
}
