//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_kf_price
    {
        public short customer_id { get; set; }
        public int item_id { get; set; }
        public string tm { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<int> pid { get; set; }
        public int id { get; set; }
        public Nullable<int> scode { get; set; }
        public Nullable<int> del_flag { get; set; }
    }
}
