//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_ls_detail
    {
        public int id { get; set; }
        public string v_code { get; set; }
        public Nullable<int> item_id { get; set; }
        public string tm { get; set; }
        public string cname { get; set; }
        public string spec { get; set; }
        public Nullable<decimal> hpack_size { get; set; }
        public Nullable<int> unit { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> jj_price { get; set; }
        public Nullable<decimal> ls_price { get; set; }
        public Nullable<decimal> yls_price { get; set; }
        public Nullable<decimal> zk { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<byte> vtype { get; set; }
        public Nullable<byte> iszs { get; set; }
        public Nullable<byte> th_flag { get; set; }
    }
}
