//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_out
    {
        public string v_code { get; set; }
        public Nullable<byte> vtype { get; set; }
        public Nullable<int> scode { get; set; }
        public Nullable<int> hs_code { get; set; }
        public Nullable<int> ywy { get; set; }
        public string remark { get; set; }
        public string srvoucher { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<System.DateTime> utime { get; set; }
        public Nullable<byte> del_flag { get; set; }
        public Nullable<byte> sh_flag { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<byte> unid { get; set; }
        public Nullable<System.DateTime> untime { get; set; }
        public Nullable<int> sh_id { get; set; }
        public Nullable<System.DateTime> sh_time { get; set; }
        public Nullable<byte> read_flag { get; set; }
        public Nullable<byte> read_cid { get; set; }
        public Nullable<System.DateTime> read_time { get; set; }
        public int id { get; set; }
    }
}
