//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_pdd_detail
    {
        public int id { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<decimal> computer_num { get; set; }
        public Nullable<decimal> pd_num { get; set; }
        public Nullable<decimal> yk_num { get; set; }
        public Nullable<decimal> ykje { get; set; }
        public Nullable<decimal> ykse { get; set; }
        public string memo { get; set; }
        public Nullable<decimal> cbje { get; set; }
        public Nullable<decimal> kcse { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<decimal> jj_price { get; set; }
        public Nullable<decimal> ls_price { get; set; }
    }
}
