//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_rkd_fk
    {
        public int ijsno { get; set; }
        public string srkno { get; set; }
        public System.DateTime drkdate { get; set; }
        public decimal dcdjsum { get; set; }
        public decimal dcrksum { get; set; }
        public decimal dcbcje { get; set; }
        public string smemo { get; set; }
        public int irkno { get; set; }
        public short x_ { get; set; }
        public Nullable<short> iDept { get; set; }
        public decimal dcmfje { get; set; }
        public decimal dcbcmfje { get; set; }
        public int itype { get; set; }
    }
}
