//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_sup_info
    {
        public int bm_code { get; set; }
        public string cname { get; set; }
        public Nullable<byte> ctype { get; set; }
        public string tel { get; set; }
        public string address { get; set; }
        public Nullable<int> yb_code { get; set; }
        public Nullable<short> hw_code { get; set; }
        public Nullable<byte> fs_code { get; set; }
        public string khzh { get; set; }
        public string bz { get; set; }
        public string sh_tn { get; set; }
        public Nullable<int> lb_code { get; set; }
        public string lxr { get; set; }
        public Nullable<byte> fp { get; set; }
        public string fax_cz { get; set; }
        public Nullable<int> hs_code { get; set; }
        public Nullable<short> phj { get; set; }
        public Nullable<float> pfzk { get; set; }
        public Nullable<byte> del_flag { get; set; }
        public Nullable<decimal> qcje { get; set; }
        public Nullable<short> qc_status { get; set; }
        public string other01 { get; set; }
        public string other02 { get; set; }
        public Nullable<byte> jsfs { get; set; }
        public Nullable<byte> js_Day { get; set; }
        public Nullable<byte> js_Pc { get; set; }
        public Nullable<byte> lockname { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<System.DateTime> utime { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<int> ywy { get; set; }
        public string itemPicture { get; set; }
    }
}
