//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_syd_detail
    {
        public int id { get; set; }
        public string code { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<decimal> jj_price { get; set; }
        public Nullable<decimal> ls_price { get; set; }
        public Nullable<decimal> hy_price { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> sjj_price { get; set; }
        public Nullable<decimal> sls_price { get; set; }
        public Nullable<decimal> shy_price { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<byte> del_flag { get; set; }
    }
}
