//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_sys_qx
    {
        public int id { get; set; }
        public Nullable<int> usr_id { get; set; }
        public Nullable<int> zm { get; set; }
        public Nullable<int> zk { get; set; }
        public string mw { get; set; }
        public Nullable<decimal> mje { get; set; }
        public string sIDcode { get; set; }
        public Nullable<System.DateTime> utime { get; set; }
    }
}
