//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_vippoint_flow
    {
        public System.DateTime dDate { get; set; }
        public int iVip { get; set; }
        public short iOpar { get; set; }
        public decimal dcPoint1 { get; set; }
        public decimal dcPoint2 { get; set; }
        public short iType { get; set; }
        public string sMemo { get; set; }
        public Nullable<int> iBillno { get; set; }
        public Nullable<int> iDept { get; set; }
    }
}
