//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_vip_item
    {
        public int id { get; set; }
        public int vipcode { get; set; }
        public string vipcard { get; set; }
        public string vipname { get; set; }
        public int item_id { get; set; }
        public string tm { get; set; }
        public string cname { get; set; }
        public decimal amount { get; set; }
        public int scode { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public string jscode { get; set; }
        public Nullable<decimal> get_count { get; set; }
    }
}
