//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_vip_type
    {
        public int id { get; set; }
        public string cname { get; set; }
        public byte zjfs { get; set; }
        public byte zkl { get; set; }
        public Nullable<short> isjf { get; set; }
        public Nullable<System.DateTime> uprq { get; set; }
        public Nullable<decimal> begin_xsje { get; set; }
        public Nullable<decimal> end_xsje { get; set; }
        public Nullable<short> isautoup { get; set; }
        public Nullable<short> iisPoint2je { get; set; }
        public Nullable<short> ibirthdaypoint { get; set; }
        public Nullable<decimal> dcpointbl { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<System.DateTime> utime { get; set; }
        public Nullable<decimal> dcBirthdayZk { get; set; }
        public Nullable<byte> del_flag { get; set; }
    }
}
