//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_vip_cz
    {
        public int vipid { get; set; }
        public string ckh { get; set; }
        public Nullable<System.DateTime> rq { get; set; }
        public Nullable<decimal> je { get; set; }
        public Nullable<decimal> dcPresentMoney { get; set; }
        public Nullable<byte> ctype { get; set; }
        public Nullable<byte> fs { get; set; }
        public Nullable<int> czr { get; set; }
        public Nullable<byte> fsd { get; set; }
        public Nullable<int> lsh { get; set; }
        public Nullable<byte> lgz { get; set; }
        public Nullable<byte> lbm { get; set; }
        public Nullable<decimal> jf { get; set; }
        public string srvoucher { get; set; }
    }
}
