//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_vip_fq
    {
        public int id { get; set; }
        public Nullable<int> vipcode { get; set; }
        public string vipcard { get; set; }
        public string vipname { get; set; }
        public Nullable<decimal> fqje { get; set; }
        public Nullable<decimal> fqsu { get; set; }
        public Nullable<decimal> mqje { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<int> scode { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<System.DateTime> valitime { get; set; }
    }
}
