//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_vip_info
    {
        public int vipcode { get; set; }
        public string vipcard { get; set; }
        public string vipname { get; set; }
        public string id_no { get; set; }
        public string tel { get; set; }
        public Nullable<byte> viptype { get; set; }
        public Nullable<int> cstatus { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<decimal> ljxfje { get; set; }
        public int zkh { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<System.DateTime> utime { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<decimal> yje { get; set; }
        public Nullable<short> dept_id { get; set; }
        public Nullable<short> zkl { get; set; }
        public Nullable<int> password { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<short> hyjb { get; set; }
        public Nullable<short> hysj { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Email { get; set; }
        public Nullable<short> date_void { get; set; }
        public Nullable<short> iczk_void { get; set; }
        public Nullable<decimal> czk_ye { get; set; }
        public Nullable<decimal> jfnum { get; set; }
        public Nullable<decimal> bdje { get; set; }
        public string other1 { get; set; }
        public string other2 { get; set; }
        public string other3 { get; set; }
        public string other4 { get; set; }
        public byte[] picture { get; set; }
        public string sVipMemo { get; set; }
        public Nullable<System.DateTime> dtbirthday_lan { get; set; }
        public Nullable<decimal> dcMaxQk { get; set; }
        public Nullable<System.DateTime> dtMaxChanged { get; set; }
        public Nullable<System.DateTime> ClearDate { get; set; }
        public Nullable<System.DateTime> validate { get; set; }
        public Nullable<byte> del_flag { get; set; }
    }
}
