//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_yh_detail
    {
        public int id { get; set; }
        public string v_code { get; set; }
        public int item_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> xg_amount { get; set; }
        public Nullable<decimal> ls_price { get; set; }
        public Nullable<decimal> zk { get; set; }
        public Nullable<int> zs_item_id { get; set; }
        public string tm { get; set; }
        public string cname { get; set; }
        public Nullable<decimal> yls_price { get; set; }
        public Nullable<decimal> yjj_price { get; set; }
        public string zs_tm { get; set; }
        public string zs_cname { get; set; }
        public Nullable<decimal> zs_yprice { get; set; }
        public Nullable<decimal> zs_ylsprice { get; set; }
        public Nullable<System.DateTime> sbegintime { get; set; }
        public Nullable<System.DateTime> sendtime { get; set; }
        public Nullable<byte> del_flag { get; set; }
        public Nullable<byte> ifxg { get; set; }
        public Nullable<decimal> add_price { get; set; }
        public Nullable<decimal> zs_amount { get; set; }
        public Nullable<byte> te_zhe { get; set; }
        public Nullable<double> lykl { get; set; }
    }
}
