//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class HjnDemoData
    {
        public int Order { get; set; }
        public string BarCode { get; set; }
        public string Goods { get; set; }
        public string Unit { get; set; }
        public string spec { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Pinyin { get; set; }
    }
}
