//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_func
    {
        public int menu_id { get; set; }
        public string menu_name { get; set; }
        public string pinyin { get; set; }
        public bool type { get; set; }
        public Nullable<byte> menu { get; set; }
        public Nullable<byte> sort { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string func_id { get; set; }
        public Nullable<bool> is_sep { get; set; }
        public byte status { get; set; }
        public int id { get; set; }
        public byte usrtype { get; set; }
        public Nullable<byte> ctype { get; set; }
    }
}
