//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class send_msg
    {
        public int seq { get; set; }
        public Nullable<int> m_id { get; set; }
        public string str_mobile { get; set; }
        public string msg { get; set; }
        public string usr_id { get; set; }
        public string password { get; set; }
        public string src { get; set; }
        public Nullable<bool> state { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<System.DateTime> msn_date { get; set; }
        public Nullable<int> flow_his_id { get; set; }
        public Nullable<int> flow_usr_id { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<bool> send_status { get; set; }
        public Nullable<System.DateTime> send_time { get; set; }
    }
}
