//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class setting
    {
        public int id { get; set; }
        public Nullable<int> info_type { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public string memo { get; set; }
        public string html_type { get; set; }
        public string mtc_t_type { get; set; }
    }
}
