//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int usr_id { get; set; }
        public string barCode { get; set; }
        public string login_id { get; set; }
        public string usr_name { get; set; }
        public string pinyin { get; set; }
        public string memo { get; set; }
        public string password { get; set; }
        public Nullable<byte> status { get; set; }
        public string contact { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public string last_ip { get; set; }
        public Nullable<int> use_count { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<System.DateTime> utime { get; set; }
        public Nullable<int> dept_id { get; set; }
        public string e_mail { get; set; }
        public string mobil { get; set; }
        public string tel { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<bool> del_flag { get; set; }
        public Nullable<byte> isadmin { get; set; }
        public Nullable<bool> is_dept_admin { get; set; }
        public string city { get; set; }
        public Nullable<byte> sex { get; set; }
        public Nullable<byte> regType { get; set; }
        public string pic_ext { get; set; }
        public string guid { get; set; }
        public Nullable<bool> binding { get; set; }
        public int h_bonus { get; set; }
        public string true_name { get; set; }
        public string inviteRandom { get; set; }
        public Nullable<double> f_last_login { get; set; }
        public byte usr_type { get; set; }
        public string d_code { get; set; }
        public Nullable<int> unit_id { get; set; }
        public string cookie { get; set; }
        public string IMEI { get; set; }
        public string cookid { get; set; }
        public string pic { get; set; }
        public Nullable<int> user_type { get; set; }
        public string ip { get; set; }
        public string job_title { get; set; }
        public Nullable<byte> Permission { get; set; }
        public string idcard { get; set; }
        public string headimgurl { get; set; }
        public string openid { get; set; }
        public Nullable<int> sort { get; set; }
        public string emp_code { get; set; }
        public string xueli { get; set; }
        public Nullable<System.DateTime> in_time { get; set; }
        public Nullable<System.DateTime> out_time { get; set; }
        public string home { get; set; }
        public Nullable<int> state { get; set; }
    }
}
