//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_deptLevelName
    {
        public int id { get; set; }
        public Nullable<byte> ilevel { get; set; }
        public string cname { get; set; }
        public string twoLevel { get; set; }
        public string threeLevel { get; set; }
    }
}
