//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_hd_item_info
    {
        public int item_id { get; set; }
        public string tm { get; set; }
        public string ftm { get; set; }
        public string cname { get; set; }
        public string spec { get; set; }
        public Nullable<int> lb_code { get; set; }
        public string manufactory { get; set; }
        public Nullable<int> unit { get; set; }
        public Nullable<decimal> hpack_size { get; set; }
        public decimal jj_price { get; set; }
        public decimal hy_price { get; set; }
        public decimal ls_price { get; set; }
        public Nullable<decimal> pf_price { get; set; }
        public Nullable<decimal> cx_price { get; set; }
        public Nullable<decimal> yl_price { get; set; }
        public string hjcode { get; set; }
        public Nullable<int> tsame { get; set; }
        public Nullable<short> slimit { get; set; }
        public Nullable<short> xlimit { get; set; }
        public string brand { get; set; }
        public Nullable<short> supplier { get; set; }
        public Nullable<short> isale { get; set; }
        public Nullable<decimal> qc_store { get; set; }
        public Nullable<decimal> vip_price2 { get; set; }
        public Nullable<decimal> vip_price3 { get; set; }
        public Nullable<decimal> pf_price2 { get; set; }
        public Nullable<decimal> pf_price3 { get; set; }
        public string manufacturer { get; set; }
        public string pack_sn { get; set; }
        public Nullable<byte> db_flag { get; set; }
        public Nullable<byte> status { get; set; }
    }
}
