//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_hd_istore
    {
        public int scode { get; set; }
        public int item_id { get; set; }
        public Nullable<decimal> samount { get; set; }
        public Nullable<decimal> jj_price { get; set; }
        public Nullable<decimal> ls_price { get; set; }
        public Nullable<decimal> hy_price { get; set; }
        public Nullable<decimal> slimit { get; set; }
        public Nullable<decimal> xlimit { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> pf_price { get; set; }
    }
}
