//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_hd_ls
    {
        public int id { get; set; }
        public string v_code { get; set; }
        public Nullable<int> vip { get; set; }
        public Nullable<decimal> zzk { get; set; }
        public Nullable<byte> del_flag { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<int> ywy { get; set; }
        public Nullable<int> scode { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
    }
}
