//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_item_pack
    {
        public int item_id { get; set; }
        public int sitem_id { get; set; }
        public decimal pack_amount { get; set; }
        public Nullable<decimal> pack_size { get; set; }
    }
}
