//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_xs_item_info
    {
        public int item_id { get; set; }
        public string tm { get; set; }
        public string cname { get; set; }
        public string spec { get; set; }
        public string dw { get; set; }
        public string jj_price { get; set; }
        public string ls_price { get; set; }
        public string hy_price { get; set; }
        public decimal xg_amount { get; set; }
        public string memo { get; set; }
        public int scode { get; set; }
        public int vtype { get; set; }
        public string ftm { get; set; }
        public int lb_code { get; set; }
        public string pp { get; set; }
    }
}
