//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hjn20160520
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_yh_detail
    {
        public Nullable<int> scode { get; set; }
        public int vtype { get; set; }
        public int viptype { get; set; }
        public int dx_type { get; set; }
        public Nullable<byte> tj_range { get; set; }
        public Nullable<int> limit_times { get; set; }
        public Nullable<decimal> zjmoney { get; set; }
        public Nullable<decimal> zsmoney { get; set; }
        public Nullable<byte> ifxg { get; set; }
        public decimal xg_amount { get; set; }
        public int item_id { get; set; }
        public string tm { get; set; }
        public string cname { get; set; }
        public Nullable<decimal> ls_price { get; set; }
        public decimal amount { get; set; }
        public int zs_item_id { get; set; }
        public string zstm { get; set; }
        public string zs_cname { get; set; }
        public Nullable<decimal> zs_amount { get; set; }
        public Nullable<decimal> zs_yprice { get; set; }
        public decimal yjj_price { get; set; }
        public decimal yls_price { get; set; }
        public Nullable<System.DateTime> sbegintime { get; set; }
        public Nullable<System.DateTime> sendtime { get; set; }
        public string memo { get; set; }
    }
}
